CREATE DATABASE IF NOT EXISTS carro_db;
USE carro_db;

CREATE TABLE carro (
  id SERIAL PRIMARY KEY,
  marca VARCHAR(255) NOT NULL,
  modelo VARCHAR(255) NOT NULL,
  ano VARCHAR(255) NOT NULL,
  cor VARCHAR(255) NOT NULL,
  preco VARCHAR(255) NOT NULL
);